name: ficcanaso
description: The Dart analyzer settings and best practices used. forked from pedantic
version: 2.0.1
repository: https://github.com/dbbd59/ficcanaso

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pedantic: ^1.11.0
