name: ficcanaso
description: The Dart analyzer settings and best practices used. forked from pedantic
version: 2.0.7
repository: https://github.com/dbbd59/ficcanaso

environment:
  sdk: ">=2.12.0 <3.0.0"