name: ficcanaso
description: The Dart analyzer settings and best practices used. forked from pedantic
version: 2.0.2
repository: https://github.com/dbbd59/ficcanaso

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pedantic: ^1.11.0
